disabled_rules:
    - colon
    - comma
    - control_statement
    - force_cast
    - force_try
    - identifier_name
    - nesting
    - weak_delegate
    - multiple_closures_with_trailing_closure
    - trailing_whitespace
opt_in_rules:
    - missing_docs
excluded:
    - Carthage
    - Pods
    - R.generated.swift
line_length:
    warning: 150
    error: 200
    ignores_function_declarations: true
    ignores_interpolated_strings: true
    ignores_urls: true
